### ISSUE TITLE
Validation master issue

### ISSUE THREAD

**Issue by vladimir-kotikov** [foreverest/mobile-center-cli#13]
We plan to do a daily project validation, e.g. take 2-3 random projects from these lists:

- iOS: https://github.com/dkhamsing/open-source-ios-apps
- Android: https://github.com/pcqpcq/open-source-android-apps

for every supported platform/os and perform manual testing for some selected scenarios.

---
Below is the list of cases to test. All tests are going to be performed in sequence without cleaning any results of previous ones. After performing each step we verify the results. If any of them are invalid, we document the case and do not perform the rest of the steps.

1) Integrate an arbitary module (analytics, crashes or distribute)
2) Integrate all three modules
3) Integrate two arbitary modules
4) Modify each affected file (_e.g. build.gradle & MainActivity.java for Android project_) manually. Modification should not break the correctness of the code but it should move declarations, statements and method calls in other (valid) places. For example, in MainActivity.java file: 
    - move a couple (not all) of `import` statements several lines up
    - move `MobileCenter.start(...)` call in other place within the same method
    - make `MobileCenter.start(...)` call be written in one line
5) Run the last command again
---
Below is the list of already tested apps with linked issues (if there are any):

---
iOS - Swift/Objective-C:

- Artsy Shows - PASS
- EX Player - PASS
- GrandCentralBoard - PASS
- iCook TV - PASS
- Provenance - PASS
- RailsCasts - PASS
- Retro Skate - PASS
- Telemat-tvOS - PASS
- UitzendingGemist by 4np - PASS
- UitzendingGemist by jeffkreeftmeijer - PASS

---
Android - Java

- [x] hitherejoe/Vineyard - Main activity is not found. **#40 - fixed**
- [x] XiaoMi/android_tv_metro  - Not able to recognize the project. **Not a Gradle build system**
- [x] 9elements/9elements-One-for-Android-Wear - Main activity is not found. **#41 - fixed**
- [ ] prempalsingh/arcade-watchface - Main activity is not found. **#42 - not fixed yet**
- [ ] dwa012/WearBinaryWatchFace - Main activity is not found. **#42 - not fixed yet**
- [ ] romannurik/FORMWatchFace - Main activity is not found. **#42 - not fixed yet**
- [ ] OhMyLob/LapseFace - Main activity is not found. **#42 - not fixed yet**

---

**Comment by vladimir-kotikov** [comment]
@DenisKudelin please take a look. I'd suggest starting w/ 2 randomly chosen iOS and Android apps and file any integration issues you might find

**Comment by vladimir-kotikov** [comment]
@foreverest could you please document matrix (or list) of cases that we need to test against each platform

**Comment by DenisKudelin** [comment]
Artsy Shows  - PASS
EX Player  - PASS
GrandCentralBoard  - PASS
iCook TV  - PASS
Provenance  - PASS
RailsCasts  - PASS
Retro Skate  - PASS
Telemat-tvOS  - PASS
UitzendingGemist by 4np  - PASS
UitzendingGemist by jeffkreeftmeijer  - PASS

**Comment by vladimir-kotikov** [comment]
@DenisKudelin, please add the information above to the issue itself (I believe you have permissions to edit existing issues). Also please add some details to each entry (platform/OS)
